### PR TITLE
Fix tests

### LINKED ISSUE #308: Testing suite issues
A change of the behavior of tests has happened in at https://github.com/ziglang/zig/commit/59f9253d94331cedd4d0518250c8094a064f6cd2;

therefore, a big part of the testing suit is broken;

I will create a PR that will close this issue

### PR DESCRIPTION
**Pull request by ghost**
This pull request fixes https://github.com/ZystemOS/pluto/issues/308

### CODE REVIEW

**Comment by ghost** [comment]
I happen to be stuck right here, I am having 
```
./src/kernel/arch/x86/irq.zig:44:44: error: return type '@typeInfo(@typeInfo(@TypeOf(irqHandler)).Fn.return_type.?).ErrorUnion.error_set!usize' not allowed in function with calling convention 'C'
export fn irqHandler(ctx: *arch.CpuState) !usize {
                                           ^
```

**Comment by SamTebbs33** [comment]
> I happen to be stuck right here, I am having
> 
> ```
> ./src/kernel/arch/x86/irq.zig:44:44: error: return type '@typeInfo(@typeInfo(@TypeOf(irqHandler)).Fn.return_type.?).ErrorUnion.error_set!usize' not allowed in function with calling convention 'C'
> export fn irqHandler(ctx: *arch.CpuState) !usize {
>                                            ^
> ```

Yeah I don't think the IRQ handler should be returning an error. It seems like you've made a function return an error somewhere where it would be best to catch it and panic instead. See my progress on this issue for reference

[diff.txt](https://github.com/ZystemOS/pluto/files/6485098/diff.txt)

**Comment by ghost** [comment]
I have gone too far into modifying everything

**Comment by DrDeano** [comment]
How is this coming?

**Comment by ghost** [comment]
Sorry have been busy with life and needed to take a little pause away from Zig, I'm starting to slowly get back at it. If y'all wanna finish this PR to stop it from blocking the builds feel free.

**Comment by DrDeano** [comment]
No problem, we haven't been that active either, life is pain 😆. I'll have a look at finishing this, thanks for the help 😄.

**Comment by SamTebbs33** [comment]
Closed by #310

**Pull request closed without merging**
