### PR TITLE
Feature/zig update

### PR DESCRIPTION
**Pull request by iamgweej**
I've updated to the latest zig, which broke the build, this is supposed to fix that

### CODE REVIEW

**Comment by DrDeano** [comment]
This fix has been included in #267

**Comment by SamTebbs33** [comment]
> This fix has been included in #267

I probably should have made those changes in a separate PR anyway. I'm cool with this going in if you are @DrDeano ?

**Comment by DrDeano** [comment]
Yeh, keep these updates separate from feature PR, so merge this one 👍

**Review by DrDeano — APPROVED** [review]

**Comment by SamTebbs33** [comment]
Thanks @iamgweej !

**Pull request merged**
