### PR TITLE
Added file closing in VFS functions

### PR DESCRIPTION
**Pull request by iamgweej**
I've added my fixes to the open file leaks in the VFS functions, it might not be all the functions that contain this kind of leaks.

### CODE REVIEW

**Review by SamTebbs33 — CHANGES_REQUESTED** [review]
This is great, thanks. To make sure we don't break this behaviour in the future, could you amend the `traversePath` test to make sure that no files and directories remain open? You could add a counter variable to TestFS to keep track of the number of opened nodes if you'd like.

**Comment by SamTebbs33** [comment]
Closes #220

**Comment by iamgweej** [comment]
I think I've added the appropriate test for this feature, maybe a separate issue should be opened about the design of the vfs, for example, we can't close a directory.

**Comment by SamTebbs33** [comment]
Thanks, that looks good to me. I'll give @DrDeano a bit of time to look at it before approving the merge.

**Comment by SamTebbs33** [comment]
> [...] maybe a separate issue should be opened about the design of the vfs, for example, we can't close a directory.

Sure! Feel free to open one so it can be discussed.

**Review by DrDeano — APPROVED** [review]
Looks good to me :)

**Review by SamTebbs33 — APPROVED** [review]

**Comment by SamTebbs33** [comment]
Thanks @iamgweej. Don't forget to squash your commits into one before merging!

**Comment by iamgweej** [comment]
It doesn't seem like I have merge access, would you mind merging and squashing for me? Or would you like me to push it to my fork of `develop` and open a PR from there?

**Comment by SamTebbs33** [comment]
> It doesn't seem like I have merge access, would you mind merging and squashing for me? Or would you like me to push it to my fork of `develop` and open a PR from there?

I can merge it for you and we can look into the settings to see how we give others merge access. Thanks again!

**Pull request merged**
