### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ghost**
Fixes a typo in the shell script to generate the iso file

### CODE REVIEW

**Comment by DrDeano** [comment]
The Github actions didn't run. I think you need to enable actions in your fork.

**Comment by ghost** [comment]
This is weird, I have manually enabled them and have tried to trigger it manually but I don't see the button for it;
I think an event needs to be explicitly configured for manual triggers to work

**Comment by SamTebbs33** [comment]
Hmm we've had issues with checks not running for PRs from forks but I thought they were fixed 🤔 I'm happy to approve this as it has no change to functionality. Perhaps we should move to a different service for running checks.

**Comment by ghost** [comment]
in that case I'd recommend Travis CI, the integration to GitHub is pretty seamless / painless (This might be totally unrelated but I think it'd be a good idea to ship a Dockerfile as an environment to build the ISO in, I can also make it :thinking:)

**Review by DrDeano — APPROVED** [review]
Yeh, as this has no build changes, this can be merged 🚀

**Comment by SamTebbs33** [comment]
Thanks @InfRandomness  :)

**Pull request merged**
