### PR TITLE
Feature/x86 64 port

### PR DESCRIPTION
**Pull request by ghost**
Merge the develop branch containing this [fix](https://github.com/ZystemOS/pluto/pull/300) to feature/x86_64-port;

This would fix the compilation issues occurring in this branch as well; (and would make it usable for creating new branches from it)

### CODE REVIEW

**Comment by ghost** [comment]
I have tried doing the same for feature/aarch64-port but it caused too many issues and I am afraid of breaking things up ever since I am not really good with git, although, it would be good to merge develop to this branch too.

**Review by DrDeano — APPROVED** [review]

**Comment by SamTebbs33** [comment]
> I have tried doing the same for feature/aarch64-port but it caused too many issues and I am afraid of breaking things up ever since I am not really good with git, although, it would be good to merge develop to this branch too.

Yeah I haven't worked on the aarch64 port in a few months so it's far behind develop, but I'll rebase it when I get back to aarch64.

**Comment by ghost** [comment]
Well, I wanted to do some work on it, for an uefi bootloader

**Comment by SamTebbs33** [comment]
> Well, I wanted to do some work on it, for an uefi bootloader

That would be cool :) I've just rebased and pushed

**Pull request merged**
