### PR TITLE
Feature/arch init gdt idt

### PR DESCRIPTION
**Pull request by DrDeano**
This adds the GDT, TSS and IDT implementations for the 64 bit port.
Part of #169

### CODE REVIEW

**Review by SamTebbs33 — COMMENTED** [review]
Lots of the functions and constants are the same as in 32 bit so can we share them instead of copying them?

**Comment by DrDeano** [comment]
I was thinking about this, but will probably have to reorder the arch folder structure. Would:
|- arch
     |--- x86
     |        |--- 32bit
     |        |--- 64bit
     |        |--- common
     |--- arm

So if we wanted to support 32 bit arm, then can follow the came structure. What do you think?

**Comment by SamTebbs33** [comment]
> I was thinking about this, but will probably have to reorder the arch folder structure. Would:
> |- arch
> |--- x86
> | |--- 32bit
> | |--- 64bit
> | |--- common
> |--- arm
> 
> So if we wanted to support 32 bit arm, then can follow the came structure. What do you think?

Yeah that looks good to me. Having a dir for common code would be cleaner than the 64 bit port referencing 32 bit stuff.

**Review by SamTebbs33 — APPROVED** [review]
Feel free to make the dir structure changes in this PR or a future one.

**Comment by DrDeano** [comment]
> 
> 
> Feel free to make the dir structure changes in this PR or a future one.

I shall do in another PR

**Pull request merged**
